#!/usr/bin/env python3
"""Generate a clean, user-facing changelog page from CHANGELOG.md.

Reads the raw CHANGELOG.md (generated by Python Semantic Release),
filters out internal noise, collapses duplicates, groups by minor
version, and outputs a VitePress-ready docs-site/changelog.md.

Usage:
    python gen-changelog.py          # from project root
    python docs-site/.vitepress/scripts/gen-changelog.py
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

# ── Paths ────────────────────────────────────────────────
SCRIPTS_DIR = Path(__file__).resolve().parent
DOCS_SITE = SCRIPTS_DIR.parent.parent
PROJECT_ROOT = DOCS_SITE.parent
CHANGELOG_PATH = PROJECT_ROOT / "CHANGELOG.md"
OUTPUT_PATH = DOCS_SITE / "changelog.md"

# ── Filtering rules ─────────────────────────────────────

# Section types to include in the public changelog
INCLUDE_SECTIONS = {"Features", "Bug Fixes", "Breaking Changes", "Documentation", "Performance"}

# Map raw section headings from Semantic Release to our public categories
SECTION_MAP = {
    "Features": "Features",
    "Bug Fixes": "Bug Fixes",
    "Breaking Changes": "Breaking Changes",
    "Documentation": "Documentation",
    "Performance Improvements": "Performance",
    "BREAKING CHANGE": "Breaking Changes",
}

# Sections that are always excluded (internal noise)
EXCLUDE_SECTIONS = {"Chores", "Code Style", "Continuous Integration", "Tests", "Build"}

# Cloud-only scopes not in the OSS export
CLOUD_ONLY_SCOPES = {"sre", "billing", "stripe", "auth0"}

# Internal-only scopes (not user-facing even if under Features/Bug Fixes)
INTERNAL_SCOPES = {"test", "ci"}

# Patterns for PR review round-trip entries to collapse
PR_FEEDBACK_PATTERNS = [
    re.compile(r"address.*PR.*feedback", re.IGNORECASE),
    re.compile(r"address.*PR.*comment", re.IGNORECASE),
    re.compile(r"address.*review", re.IGNORECASE),
    re.compile(r"address.*round[- ]?\d+", re.IGNORECASE),
    re.compile(r"address.*code review", re.IGNORECASE),
    re.compile(r"address.*reviewer", re.IGNORECASE),
    re.compile(r"address.*findings", re.IGNORECASE),
]

# Entries that are pure noise and should always be removed
NOISE_PATTERNS = [
    re.compile(r"^regenerate uv\.lock", re.IGNORECASE),
    re.compile(r"^update uv\.lock", re.IGNORECASE),
    re.compile(r"^retrigger CI", re.IGNORECASE),
    re.compile(r"^trigger preview rebuild", re.IGNORECASE),
    re.compile(r"^(fix|resolve|apply)?\s*ruff (lint|format)", re.IGNORECASE),
    re.compile(r"^ruff format", re.IGNORECASE),
    re.compile(r"^snapshot v[\d.]+ docs", re.IGNORECASE),
    re.compile(r"^update specs based on", re.IGNORECASE),
]

# ── Link rewriting ───────────────────────────────────────
PRIVATE_REPO_URL = "github.com/canonhq/canon-private"
PUBLIC_REPO_URL = "github.com/canonhq/canon"


# ── Data types ───────────────────────────────────────────


class Entry:
    """A single changelog entry (one bullet point)."""

    def __init__(self, text: str, pr_number: str | None = None):
        self.text = text
        self.pr_number = pr_number

    def __repr__(self) -> str:
        return f"Entry({self.text[:50]!r})"


class Version:
    """A single version heading with categorized entries."""

    def __init__(self, version: str, date: str):
        self.version = version
        self.date = date
        self.sections: dict[str, list[Entry]] = defaultdict(list)

    @property
    def minor_key(self) -> str:
        """Extract minor version key, e.g. 'v1.26' from 'v1.26.3'."""
        match = re.match(r"(v\d+\.\d+)", self.version)
        return match.group(1) if match else self.version


# ── Parsing ──────────────────────────────────────────────


def parse_changelog(text: str) -> list[Version]:
    """Parse CHANGELOG.md into a list of Version objects."""
    versions: list[Version] = []
    current_version: Version | None = None
    current_section: str | None = None
    current_entry_lines: list[str] = []

    def flush_entry():
        nonlocal current_entry_lines
        if current_entry_lines and current_version and current_section:
            full_text = " ".join(line.strip() for line in current_entry_lines)
            pr_match = re.search(r"\[#(\d+)\]", full_text)
            pr_number = pr_match.group(1) if pr_match else None
            current_version.sections[current_section].append(
                Entry(text=full_text, pr_number=pr_number)
            )
        current_entry_lines = []

    for line in text.splitlines():
        # Version heading: ## v1.26.0 (2026-03-21)
        version_match = re.match(r"^## (v[\d.]+)\s*\((\d{4}-\d{2}-\d{2})\)", line)
        if version_match:
            flush_entry()
            current_section = None
            current_version = Version(
                version=version_match.group(1),
                date=version_match.group(2),
            )
            versions.append(current_version)
            continue

        # Section heading: ### Features
        section_match = re.match(r"^### (.+)$", line)
        if section_match:
            flush_entry()
            current_section = section_match.group(1).strip()
            continue

        # Entry start: - Some text
        if line.startswith("- "):
            flush_entry()
            current_entry_lines = [line[2:]]
            continue

        # Continuation line (indented, part of a multi-line entry)
        if line.startswith("  ") and current_entry_lines:
            current_entry_lines.append(line)
            continue

        # Blank or other line
        if not line.strip():
            flush_entry()

    flush_entry()
    return versions


# ── Filtering ────────────────────────────────────────────


def is_noise(text: str) -> bool:
    """Check if an entry matches noise patterns."""
    # Strip leading scope prefix for matching: "**sre**: blah" -> "blah"
    clean = re.sub(r"^\*\*\w+\*\*:\s*", "", text)
    return any(p.search(clean) for p in NOISE_PATTERNS)


def is_pr_feedback(text: str) -> bool:
    """Check if an entry is a PR review round-trip."""
    clean = re.sub(r"^\*\*\w+\*\*:\s*", "", text)
    return any(p.search(clean) for p in PR_FEEDBACK_PATTERNS)


def has_excluded_scope(text: str) -> bool:
    """Check if an entry is scoped to a cloud-only or internal-only module."""
    scope_match = re.match(r"^\*\*(\w+)\*\*:", text)
    if scope_match:
        scope = scope_match.group(1).lower()
        return scope in CLOUD_ONLY_SCOPES or scope in INTERNAL_SCOPES
    return False


def filter_entries(versions: list[Version]) -> list[Version]:
    """Filter out internal noise, cloud-only, and excluded sections."""
    filtered: list[Version] = []

    for version in versions:
        new_version = Version(version.version, version.date)

        for section_name, entries in version.sections.items():
            # Skip excluded section types entirely
            if section_name in EXCLUDE_SECTIONS:
                continue

            # Map to public category name
            public_name = SECTION_MAP.get(section_name)
            if public_name is None:
                continue

            for entry in entries:
                if is_noise(entry.text):
                    continue
                if is_pr_feedback(entry.text):
                    continue
                if has_excluded_scope(entry.text):
                    continue
                new_version.sections[public_name].append(entry)

        # Only keep versions that have at least one entry
        if any(new_version.sections.values()):
            filtered.append(new_version)

    return filtered


# ── Deduplication ────────────────────────────────────────


def collapse_duplicates(versions: list[Version]) -> list[Version]:
    """Collapse duplicate entries sharing the same PR number within a version."""
    for version in versions:
        for section_name in list(version.sections.keys()):
            entries = version.sections[section_name]
            seen_prs: dict[str, Entry] = {}
            deduped: list[Entry] = []

            for entry in entries:
                if entry.pr_number:
                    if entry.pr_number not in seen_prs:
                        seen_prs[entry.pr_number] = entry
                        deduped.append(entry)
                    else:
                        # Keep the longer/more descriptive entry
                        existing = seen_prs[entry.pr_number]
                        if len(entry.text) > len(existing.text):
                            deduped[deduped.index(existing)] = entry
                            seen_prs[entry.pr_number] = entry
                else:
                    # No PR number — check for near-duplicate text
                    normalized = re.sub(r"\s+", " ", entry.text.lower().strip())
                    is_dup = False
                    for existing in deduped:
                        existing_norm = re.sub(r"\s+", " ", existing.text.lower().strip())
                        if normalized == existing_norm:
                            is_dup = True
                            break
                    if not is_dup:
                        deduped.append(entry)

            version.sections[section_name] = deduped

    return versions


# ── Grouping ─────────────────────────────────────────────


def group_by_minor(versions: list[Version]) -> list[tuple[str, dict[str, list[Entry]]]]:
    """Group versions by minor version (e.g. v1.26.x -> v1.26).

    Returns list of (minor_key, merged_sections) tuples, ordered by version desc.
    """
    groups: dict[str, dict[str, list[Entry]]] = {}
    group_order: list[str] = []

    for version in versions:
        key = version.minor_key
        if key not in groups:
            groups[key] = defaultdict(list)
            group_order.append(key)

        for section_name, entries in version.sections.items():
            groups[key][section_name].extend(entries)

    # Deduplicate again within the merged minor version group
    result: list[tuple[str, dict[str, list[Entry]]]] = []
    for key in group_order:
        sections = groups[key]
        # Create a temporary Version to reuse collapse logic
        tmp = Version(key, "")
        tmp.sections = dict(sections)
        collapse_duplicates([tmp])
        result.append((key, dict(tmp.sections)))

    return result


# ── Link rewriting ───────────────────────────────────────


def rewrite_links(text: str) -> str:
    """Replace private repo URLs with public repo URLs."""
    return text.replace(PRIVATE_REPO_URL, PUBLIC_REPO_URL)


def strip_entry_links(text: str) -> str:
    """Strip PR and commit links from an entry, keeping just the description."""
    # Remove trailing PR/commit link block: ([#123](url), [`abc`](url))
    cleaned = re.sub(r"\s*\(\[#\d+\]\([^)]+\),?\s*\[`[a-f0-9]+`\]\([^)]+\)\)", "", text)
    # Remove standalone commit link: ([`abc`](url))
    cleaned = re.sub(r"\s*\(\[`[a-f0-9]+`\]\([^)]+\)\)", "", cleaned)
    # Remove standalone PR link: ([#123](url))
    cleaned = re.sub(r"\s*\(\[#\d+\]\([^)]+\)\)", "", cleaned)
    return cleaned.strip()


def clean_scope_prefix(text: str) -> str:
    """Convert **scope**: text to readable format."""
    match = re.match(r"^\*\*(\w+)\*\*:\s*(.+)", text)
    if match:
        scope, rest = match.group(1), match.group(2)
        # Capitalize first letter of the rest
        rest = rest[0].upper() + rest[1:] if rest else rest
        return f"{rest} ({scope})"
    return text


# ── Rendering ────────────────────────────────────────────

# Preferred section order in output
SECTION_ORDER = ["Breaking Changes", "Features", "Bug Fixes", "Performance", "Documentation"]


def render_markdown(groups: list[tuple[str, dict[str, list[Entry]]]]) -> str:
    """Render grouped changelog data as a VitePress markdown page."""
    lines = [
        "---",
        "title: Changelog",
        "---",
        "",
        "# Changelog",
        "",
        "Notable changes to Canon, grouped by minor release.",
        "",
    ]

    for minor_key, sections in groups:
        lines.append(f"## {minor_key}")
        lines.append("")

        # Output sections in preferred order
        for section_name in SECTION_ORDER:
            entries = sections.get(section_name, [])
            if not entries:
                continue

            lines.append(f"### {section_name}")
            lines.append("")

            for entry in entries:
                clean = strip_entry_links(entry.text)
                clean = clean_scope_prefix(clean)
                lines.append(f"- {clean}")

            lines.append("")

    return "\n".join(lines)


# ── Main ─────────────────────────────────────────────────


def main():
    if not CHANGELOG_PATH.exists():
        print(f"CHANGELOG.md not found at {CHANGELOG_PATH}", file=sys.stderr)
        sys.exit(1)

    raw = CHANGELOG_PATH.read_text(encoding="utf-8")

    # Parse → Filter → Deduplicate → Group → Rewrite → Render
    versions = parse_changelog(raw)
    versions = filter_entries(versions)
    versions = collapse_duplicates(versions)
    groups = group_by_minor(versions)
    markdown = render_markdown(groups)
    markdown = rewrite_links(markdown)

    OUTPUT_PATH.write_text(markdown, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH} ({len(groups)} minor versions)")


if __name__ == "__main__":
    main()
