apiVersion: v2
name: canon
description: "Canon — spec-driven development platform"
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: CanonHQ
keywords:
  - specs
  - ai
  - github
  - documentation
  - canon
dependencies:
  - name: zitadel
    version: "~8.6.0"
    repository: https://charts.zitadel.com
    condition: zitadel.enabled
  - name: opensearch
    version: "~3.6.0"
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.internal.enabled
