"""Agent config file generation for multi-platform IDE integration."""

from __future__ import annotations

import re
from pathlib import Path

CANON_MARKER_START = "<!-- canon:agent-config -->"
CANON_MARKER_END = "<!-- /canon:agent-config -->"

SUPPORTED_PLATFORMS = ("claude", "cursor", "copilot", "codex", "gemini")

# Platform → relative file path for generated config
PLATFORM_CONFIG: dict[str, str] = {
    "claude": ".claude/CLAUDE.md",
    "cursor": ".cursorrules",
    "copilot": ".github/copilot-instructions.md",
    "codex": "AGENTS.md",
    "gemini": "GEMINI.md",
}


def _generate_content(platform: str) -> str:
    """Generate the agent config content for a platform."""
    lines = [
        CANON_MARKER_START,
        "",
        "## Canon Spec-Driven Development",
        "",
        "This repo uses [Canon](https://canonhq.co) for spec-driven development.",
        "Specs are structured markdown documents that define features, acceptance",
        "criteria, and implementation status.",
        "",
        "### Configuration",
        "",
        "- **Config**: `CANON.yaml` in the project root",
        "- **Specs**: See `specs.doc_paths` in CANON.yaml (default: `docs/specs/*.md`)",
        "",
        "### Accessing Specs",
        "",
    ]

    if platform in ("claude", "gemini", "codex"):
        lines.extend(
            [
                "Canon provides an MCP server with these tools:",
                "- `search` — Find specs by keyword",
                "- `get_spec` — Read a full spec with sections and acceptance criteria",
                "- `list_specs` — List all specs in the repo",
                "- `get_section` — Read a single spec section",
                "",
                "Use these tools to understand requirements before modifying code",
                "in spec-related paths.",
            ]
        )
    else:
        lines.extend(
            [
                "Use the Canon CLI to access specs:",
                "- `canon status` — Show spec coverage dashboard",
                "- `canon tasks` — List actionable spec tasks",
                "",
                "Check spec files in `docs/specs/` for requirements before modifying",
                "related code.",
            ]
        )

    lines.extend(
        [
            "",
            f"<!-- Generated by `canon setup --agent {platform}` -->",
            CANON_MARKER_END,
        ]
    )
    return "\n".join(lines) + "\n"


def generate_agent_config(
    root: Path,
    platform: str,
    force: bool = False,
) -> str:
    """Generate an agent config file for the given platform.

    Returns a status message string.
    """
    if platform not in PLATFORM_CONFIG:
        return f"Unknown platform: {platform}. Supported: {', '.join(SUPPORTED_PLATFORMS)}"

    rel_path = PLATFORM_CONFIG[platform]
    file_path = root / rel_path

    content = _generate_content(platform)

    if file_path.exists():
        existing = file_path.read_text()

        # Check for existing Canon marker — safe to replace
        if CANON_MARKER_START in existing:
            pattern = re.compile(
                re.escape(CANON_MARKER_START) + r".*?" + re.escape(CANON_MARKER_END),
                re.DOTALL,
            )
            updated = pattern.sub(content.rstrip(), existing)
            file_path.write_text(updated)
            return f"Updated Canon block in {rel_path}"

        # File exists without Canon marker — requires --force
        if not force:
            return (
                f"{rel_path} already exists with non-Canon content. "
                f"Use --force to append Canon config."
            )

        # Append Canon block
        separator = "\n\n" if not existing.endswith("\n\n") else ""
        file_path.write_text(existing + separator + content)
        return f"Appended Canon config to {rel_path}"

    # Create new file
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content)
    return f"Created {rel_path}"


def run_agent_setup(
    platforms: list[str],
    force: bool = False,
    target_dir: Path | None = None,
) -> None:
    """Generate agent config files for the specified platforms."""
    root = target_dir or Path.cwd()

    if not (root / "CANON.yaml").exists():
        print("Warning: No CANON.yaml found. Run `canon setup` first.")

    for platform in platforms:
        result = generate_agent_config(root, platform, force=force)
        print(f"  {result}")
