{{- if and .Values.opensearch.enabled (not .Values.opensearch.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canon.fullname" . }}-opensearch
  labels:
    {{- include "canon.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.opensearch.internal.enabled }}
  OPENSEARCH_USERNAME: {{ required "opensearch.internal.username must be set when opensearch.internal.enabled=true" .Values.opensearch.internal.username | quote }}
  OPENSEARCH_PASSWORD: {{ required "opensearch.internal.password must be set when opensearch.internal.enabled=true" .Values.opensearch.internal.password | quote }}
  {{- else }}
  OPENSEARCH_USERNAME: {{ required "opensearch.external.username must be set when opensearch.enabled=true and internal=false" .Values.opensearch.external.username | quote }}
  OPENSEARCH_PASSWORD: {{ required "opensearch.external.password must be set when opensearch.enabled=true and internal=false" .Values.opensearch.external.password | quote }}
  {{- end }}
{{- end }}
